### ISSUE TITLE
Distinguishing between authentication failures and empty tables

### ISSUE THREAD

**Issue by rbiswas4** [MickaelRigault/ztfquery#10]
Due to an authentication failure, I was able to run the examples:
```
from ztfquery import query
zquery = query.ZTFQuery()
zquery.load_metadata(kind="ref",radec=[276.107960, +44.130398], size=0.0001)
zquery.metatable[["field","filtercode", "ccdid","qid"]]
```
and get an empty table returned, with no warning that this was because of an authentication failure. It might be good to raise an exception when the authentication fails aside from returning an empty table.

**Comment by MickaelRigault** [comment]
moving to #16
