### ISSUE TITLE
Input points not inside the image?

### ISSUE THREAD

**Issue by rbiswas4** [MickaelRigault/ztfquery#11]
For a particular project @PhiTheta and I were using:

```
from ztfquery import query
zquery = query.ZTFQuery()
zquery.load_metadata(radec=[11.571143641059434,42.238752185138665], size=0.01)```
```
Looking at `zquery.metatable`, we can see that an image with filefracday=

field qid, ccd, filefracday, filtercode
695	1	11	20171218193113	zr
is listed. The corresponding image is `ztf_20171218193113_000695_zr_c11_o_q1_sciimg.fits`

Looking at the image using DS9 the input point seems to be (just 42.238 vs 42.234 degrees!) outside. I thought that by definition the input point should be part of the image. Is this because it is in a chip gap () and not viewed by any other quadrant and so could be called part of this image, or is there something else that I could be doing wrong.

**Comment by MickaelRigault** [comment]
Hello @rbiswas4, 

This is a problem of IRSA/IPAC that the code is querying. If the response to the query is not accurate, nothing I can do about it. Sorry.

PS: Note that `size` is in degree. Maybe it matters here (don't know).

**Comment by fmasci** [comment]
Hi,

The image in question has date: ztf_20171218193113..., i.e., commissioning.

I cannot guarantee the astrometric reconstruction (in particular FOV-distortion) was properly calibrated and tuned at that time. If you see astrometric issues in data acquired >~ Mar 1, 2018 (noting that the camera was reinstalled on Feb 2 with retuning of all pipeline parameters), please submit a help-desk ticket at https://irsasupport.ipac.caltech.edu. Include an example of your query.

Thanks, Frank

On Jul 10, 2019, at 12:52 AM, rbiswas4 <notifications@github.com<mailto:notifications@github.com>> wrote:


For a particular project @PhiTheta<https://github.com/PhiTheta> and I were using:

from ztfquery import query
zquery = query.ZTFQuery()
zquery.load_metadata(radec=[11.571143641059434,42.238752185138665], size=0.01)```

Looking at `zquery.metatable`, we can see that an image with filefracday=

field qid, ccd, filefracday, filtercode
695     1       11      20171218193113  zr
is listed. The corresponding image is `ztf_20171218193113_000695_zr_c11_o_q1_sciimg.fits`


Looking at the image using DS9 the input point seems to be (just 42.238 vs 42.234 degrees!) outside. I thought that by definition the input point should be part of the image. Is this because it is in a chip gap () and not viewed by any other quadrant and so could be called part of this image, or is there something else that I could be doing wrong.

**Comment by rbiswas4** [comment]
Sorry missed this travelling. Thanks to both of you. Will try your suggestions. Thanks!
