### ISSUE TITLE
Failing behaviour for incorrect password

### ISSUE THREAD

**Issue by robertdstein** [MickaelRigault/ztfquery#14]
The failing behaviour for `fields.has_field_reference()` is confusing. If I check a field in the primary and secondary grid, e.g 397 and 1441, but my password was entered wrong, it does not fail. Instead it tells me that the first one has references, but the second one does not, with no additional warning. However, if the password is right, it correctly tells me both have references.

**Comment by MickaelRigault** [comment]
Moving to #16
