### ISSUE TITLE
ztfquery cuts off data from 2019

### ISSUE THREAD

**Issue by MichaelMedford** [MickaelRigault/ztfquery#15]
I am getting some unexpected behavior when using obsjd in the sql_query parameter of ZTFQuery.

```
from ztfquery import query
zquery = query.ZTFQuery()
zquery.load_metadata(sql_query="obsjd>2458450.0")
obsjd = zquery.metatable.obsjd.values - 2458484.5
 # January 1, 2019
```

Plotting up the resulting dates shows that there is nothing showing up for 2019.
<img width="575" alt="Screen Shot 2019-10-02 at 3 32 47 PM" src="https://user-images.githubusercontent.com/12001188/66086755-eb8fcb00-e529-11e9-9990-33ec553332f5.png">

**Comment by MickaelRigault** [comment]
The 2019 data are not public, while the MSIP ones from 2018 are

so 2 solutions:
- 1 your irsa account is not affiliated with ZTF, so you only have access to the public data.
- 2 your irsa account is affiliated but you did a mistake when entering your account to ZTF query

To check option 2, do:
```python
from ztfquery import io
io._load_id_("irsa")
```
and see if the results are correct. If not do:
```python
io.set_account("irsa")
```

If it is correct. Contact Frank Masci to check if your account is indeed associated to ZTF

**Comment by MickaelRigault** [comment]
@MichaelMedford could you check if this is a password issue ?

**Comment by MichaelMedford** [comment]
I made two simultaneous changes, either of which may of fixed the issue. I changed my password to no longer include a special character, and I deleted the password file to generate a new one. Either way, I was able to get access to all data.

**Comment by MickaelRigault** [comment]
ok, for the future. To update your password (for instance here for irsa), simply do: 
```python
from ztfquery import io
io.set_account("irsa")
```
