### ISSUE TITLE
Night summary

### ISSUE THREAD

**Issue by rjoebruch** [MickaelRigault/ztfquery#17]
Night summary does not return data (see screenshot) 
<img width="901" alt="Screen Shot 2019-10-08 at 20 21 54" src="https://user-images.githubusercontent.com/45436034/66417783-69137980-ea09-11e9-9cdc-5cd396814d88.png">

**Comment by MichaelMedford** [comment]
This looks like it is most likely an authentication issue.
<img width="1083" alt="Screen Shot 2019-10-08 at 10 27 00 AM" src="https://user-images.githubusercontent.com/12001188/66418104-3a1fe800-e9b6-11e9-8031-99d428968ae5.png">

You can check that your login details are correct with
```
from ztfquery import io
io._load_id_("irsa")
```

If they are incorrect they can be reset with
```
io.set_account("irsa")
```

I have fixed problems like this in the past by reseting my login credentials.

**Comment by MickaelRigault** [comment]
Actually the night summary do not ask for the `irsa` account but the `ztfops` one.

Check your ztfops account using when Michael just said:

```python
from ztfquery import io
io._load_id_("ztfops")
```
and do if wrong:
```python
io.set_account("ztfops")
```

Check here for the correct password (do not put it on github!)
http://www.oir.caltech.edu/twiki_ptf/bin/view/ZTF/ZTFOps

**Comment by rjoebruch** [comment]
Hi, 

The ztfops was set on my personal user login. I now changed it to the ztfops login and it worked. I managed to query a random night summary.
Thanks! 

Will I have to set it up every time I am using the night summary?

Best
Rachel

**Comment by MickaelRigault** [comment]
Not it is now stored. So you can forget about it.
