### ISSUE TITLE
Error when using multiprocessing

### ISSUE THREAD

**Issue by annayqho** [MickaelRigault/ztfquery#18]
When running download_data with nprocess=8, ztfquery crashed with "Too many open files." I think the reason is the way multiprocessing is being run in io.py . I think it should be 

with multiprocessing.Pool(nprocess) as p:
   p.map(...)

instead of
p = multiprocessing.Pool(nprocess)
p.map(...)

because the former automatically closes the process in between.

I got the fix from here:
https://stackoverflow.com/questions/45665991/multiprocessing-returns-too-many-open-files-but-using-with-as-fixes-it-wh

**Comment by MickaelRigault** [comment]
Thanks !

**Comment by MickaelRigault** [comment]
I have implemented the change, it was a good thing to do.
Please update to get version 1.8.1

However, I am surprised the "too many files open" comes from the p= multiprocessing.pool. 
Could you test to see if it now is fixed ? 
If not please copy here the full error message. 

Thanks

**Comment by annayqho** [comment]
It seems to be working fine now!

**Comment by MickaelRigault** [comment]
greats!
