### ISSUE TITLE
Lightcurve query does not allow auth field

### ISSUE THREAD

**Issue by wyrzykow** [MickaelRigault/ztfquery#19]
I can not use ~/.ztfquery password storage. 
Specifying auth=['user','pass'] as an argument works only in query.py and download_data method there. 
However, in lightcurve.py, there is another method download_data which does not take auth argument.

**Comment by MickaelRigault** [comment]
oops, sorry, I'ml going to fix that

**Comment by MickaelRigault** [comment]
Finally done (cookie used before that)
