### ISSUE TITLE
Suggestion: Data integrity check

### ISSUE THREAD

**Issue by simeonreusch** [MickaelRigault/ztfquery#21]
Hi Mickael,

I often have the problem that the download of some files fails silently, which leaves them truncated. When opening these, astropy warns 
`WARNING: File may have been truncated: actual file length (7094272) is smaller than the expected size (10074240) [astropy.io.fits.file]`

A method to check if all downloaded files can be opened and redownload files that can't would be extremely helpful.

By the way, I switched to your ztflc-code for forced photometry and I am extremely delighted by it!

**Comment by simeonreusch** [comment]
Rahul in Stockholm would also very much appreciate this

**Comment by MickaelRigault** [comment]
Implemented. 

Currently in testing. >1.8.2
