### ISSUE TITLE
issue with ztfquery.skyvision

### ISSUE THREAD

**Issue by annayqho** [MickaelRigault/ztfquery#27]
I tried to run,
skyvision.CompletedLog.from_date("2021-06-14")

and supplied the username and password. This resulted in the error,

/global/homes/a/annaho/.conda/envs/my_env/lib/python3.8/site-packages/ztfquery/io.py:216: UserWarning: No test designed for skyvision. Cannot test if logins are correct.
  warnings.warn(f"No test designed for {which}. Cannot test if logins are correct.")
/global/homes/a/annaho/.conda/envs/my_env/lib/python3.8/site-packages/ztfquery/skyvision.py:206: UserWarning: Column format does not match the completed_log date downloade for 2021-06-14
  warnings.warn(f"Column format does not match the completed_log date downloade for {date}")
[['<!DOCTYPE', 'HTML', 'PUBLIC', '"-//W3C//DTD', 'HTML', '3.2', 'Final//EN">'], ['<title>404', 'Not', 'Found</title>'], ['<h1>Not', 'Found</h1>'], ['<p>The', 'requested', 'URL', 'was', 'not', 'found', 'on', 'the', 'server.', 'If', 'you', 'entered', 'the', 'URL', 'manually', 'please', 'check', 'your', 'spelling', 'and', 'try', 'again.</p>']]
/global/homes/a/annaho/.conda/envs/my_env/lib/python3.8/site-packages/ztfquery/skyvision.py:58: UserWarning: Download did not seem successful. Cannot retreive the completed_log for 2021-06-14
  warnings.warn(f"Download did not seem successful. Cannot retreive the {which}_log for {date}")

**Comment by simeonreusch** [comment]
Did you try the latest version? I had this issue (skyvision webpage changed), Mickael fixed it recently.

**Comment by annayqho** [comment]
Oh, thanks a lot. The update fixed it.
