### ISSUE TITLE
Problem in getting light curve (token issue)

### ISSUE THREAD

**Issue by Kushagra7777** [MickaelRigault/ztfquery#31]
In ztfquery >> tutorials >> 2. Fritz ; 2.1 get target data and plot lightcurves.ipynb.
I'm getting this OSError
![image](https://user-images.githubusercontent.com/76401345/152845059-489b90c9-fdf5-4009-b18f-4f168edd1c69.png)
.

**Comment by MickaelRigault** [comment]
Did you set your token ?

**Comment by Kushagra7777** [comment]
> Did you set your token ?

How am I suppose to do that?
I know a command **jupyter notebook list** ,which provide tokens for all running notebooks.

**Comment by MickaelRigault** [comment]
I mean, the token from fritz ?
You are using `ztfquery.fritz` which is grabbing data from the ZTF fritz service (https://fritz.science/). Do you have an account there ? 
 - If so, you have to create a token and give it to ztfquery (you have been prompted to do that the first time you used `ztfquery.fritz` ; you can reset it by using `ztfquery.io.set_account('fritz')`
 - If not, then you cannot use the ztfquery.fritz service
