### ISSUE TITLE
Downloading image cutouts instead of the full image

### ISSUE THREAD

**Issue by JTerwel** [MickaelRigault/ztfquery#34]
Usually I only need to see a small region around my object of interest. Downloading the entire image is not needed. IRSA allows one to query for a cutout, as is show near the bottom of [this](https://irsa.ipac.caltech.edu/docs/program_interface/ztf_api.html) page.

Can an option be added to ztfquery where I can ask to only download the image cutouts? This would speed up my code considerably.

**Comment by simeonreusch** [comment]
Jacco, this is brilliant.

**Comment by MickaelRigault** [comment]
Thanks for pushing this @simeonreusch I beleive it should not be that complicated to add to the url builder

**Comment by simeonreusch** [comment]
Already on it. Modifying the url is trivial. What's harder is making ztfquery respect a different parent directory (if you don't do that, running forced photometry on a source in the same field will fail, as it won't be part of the cutout).

**Comment by MickaelRigault** [comment]
Do you want the cutout service to store data ?

**Comment by simeonreusch** [comment]
Of course I do. But no worries, I'm almost done

**Comment by MickaelRigault** [comment]
Any progress on that @simeonreusch ?

**Comment by simeonreusch** [comment]
Yes, it's implemented. The keyword is `cutouts=True`. If one does this, one should also specify `download_dir` to avoid not finding objects observed with the same CCD which won't be in the cutouts.
