### ISSUE TITLE
Importing 'fields' from ztfquery produces error

### ISSUE THREAD

**Issue by casonshep** [MickaelRigault/ztfquery#35]
Hi there, I am currently working on an algorithm for Dr. Matthew Graham utilizing ztfquery. Since the August 22 updates the the Fields.py file, I am unable to properly import fields. I get this error:

~~~
File "/usr/local/lib/python3.7/dist-packages/ztfquery/fields.py", line 197 
if (inshape:=np.shape(radec))[-1] != 2:
           ^
SyntaxError: invalid syntax

**Comment by simeonreusch** [comment]
The walrus operator requires Python >= 3.8
