### ISSUE TITLE
meta data not clean by default

### ISSUE THREAD

**Issue by MickaelRigault** [MickaelRigault/ztfquery#37]
Hi @simeonreusch ,

I found another bug in your metadata implementation. The `clean` does not work for calibration data (no infobts) and the "ipac_gid>0" was the source of an issue I had with mat while downloading the metadata (missing lines). 

Anyway, I'm going to do two things:
- **clean** should not be default (by default, the code shouldn't do anything smart)
- the infobits will first be checked.

**Comment by MickaelRigault** [comment]
It seems it was already `clean=False` in the latest version. 

Why clean means ipac_gid>0 ?

**Comment by simeonreusch** [comment]
Gotcha. gid>0 means no images prior to ZTF start (they have negative program IDs). I discussed this with Mat. On 16. Feb 2023, at 09:15, Mickael Rigault ***@***.***> wrote:﻿
It seems it was already clean=False in the latest version.
Why clean means ipac_gid>0 ?

**Comment by MickaelRigault** [comment]
ipac_gid = -1 is also for all calibration files.

**Comment by simeonreusch** [comment]
I see. But that shouldn't worry too much, as `clean` is `False` by default I would say.

**Comment by MickaelRigault** [comment]
ok. I'm closing the issue. Let's make sure clean remains False as default
