### ISSUE TITLE
Bug in URL for reference images

### ISSUE THREAD

**Issue by annayqho** [MickaelRigault/ztfquery#9]
The URL for reference images is sometimes not correct. For example, for one source, the URL is
'https://irsa.ipac.caltech.edu/ibe/data/ztf/products/ref/000/field001706/zr/ccd15/q1/ztf_001706_zr_c15_q1_refimg.fits'
instead of
'https://irsa.ipac.caltech.edu/ibe/data/ztf/products/ref/001/field001706/zr/ccd15/q1/ztf_001706_zr_c15_q1_refimg.fits'

In other words, the 3-digit number after /ref/ should match the first three digits after 'field'

**Comment by MickaelRigault** [comment]
Hi Anna, 

I think the bug is fixed. (version 1.4.1).

Could you double check and let me know ?
